<html manifest="/manifest">
   <head>
      <script src="js/third_party/jquery-1.9.1.min.js"></script>
      <script src="js/third_party/pouchdb-nightly.min.js"></script>
      <script src="js/main.js"></script>
      <style>
         #add-user:hover {
            cursor: pointer;
         }

      </style>
   </head>
   <body>
      <h1>Darts!</h1>
      <img id="add-user" src="img/add_user.png">

      <div id="online-status">
      </div>
   </body>
</html>
